### ISSUE TITLE
Can you explain when to use commas?

### ISSUE THREAD

**Issue by laundry-96** [terraform-in-action/manning-code#33]
https://github.com/terraform-in-action/manning-code/blob/eca4cee612dfdc747c970a50beee7f3cd9b5d8eb/chapter4/complete/modules/autoscaling/main.tf#L65

Hi! I am really loving your book so far, but in chapter 4, I was attempting to copy all of the files line for line so I can get a feel for writing the code. However on line 65, I put commas after backend_port as well, but I was not able to reach the website. Once I double checked and removed the comma, it worked. Can you explain when you should and shouldn't use commas?

Thanks again!
  Austin DeLauney

**Comment by laundry-96** [comment]
Update: according to the module, they do not use commas at all, so I'm confused on why you use them:
https://github.com/terraform-aws-modules/terraform-aws-alb

**Comment by scottwinkler** [comment]
Hi Austin. That looks like a typo. Thank you for you for pointing this out.
